/**
 * Compatibility helpers for d8 testcases generated by reconfuzz.
 *
 * This file provides stubs for functions commonly referenced by V8 testcases
 * and historical POCs, so generated scripts can run without the full V8 test
 * harness.
 */

// Natives helpers. In a real d8 with --allow-natives-syntax these exist
// automatically; we alias them here for environments that need explicit
// declarations.
if (typeof gc === 'undefined') {
  function gc() {
    /* no-op outside d8 */
  }
}

// Common d8 natives used by generated testcases and historical POCs.
// These are no-ops outside d8; the real implementations are provided by V8
// when --allow-natives-syntax is enabled.
const NATIVES = [
  '%PrepareFunctionForOptimization',
  '%OptimizeFunctionOnNextCall',
  '%OptimizeMaglevOnNextCall',
  '%ArrayBufferDetach',
  '%FlushLiftoffCode',
  '%WasmTriggerCodeGC',
  '%WasmTriggerTierUpForTesting',
  '%WasmTierUpFunction',
  '%GenerateWasmCompilationHints',
  '%IsTurboFanFunction',
  '%GetWasmExceptionValues',
  '%HeapObjectVerify',
  '%DebugPrint',
  '%DebugPrintGeneric',
  '%DebugPrintFloat',
  '%RuntimeEvaluateREPL',
];

NATIVES.forEach((name) => {
  const short = name.slice(1);
  if (typeof globalThis[short] === 'undefined' && typeof globalThis[name] === 'undefined') {
    globalThis[short] = function () {};
  }
});

if (typeof quit === 'undefined') {
  function quit(code) {
    if (typeof process !== 'undefined') {
      process.exit(code);
    }
  }
}

// Minimal assertion helpers.
function assertEquals(expected, actual, msg) {
  if (expected !== actual) {
    throw new Error(
      (msg ? msg + ': ' : '') +
      'Expected ' + JSON.stringify(expected) +
      ' but got ' + JSON.stringify(actual)
    );
  }
}

function assertThrows(fn, type, msg) {
  let threw = false;
  try {
    fn();
  } catch (e) {
    threw = true;
    if (type && !(e instanceof type)) {
      throw new Error(
        (msg ? msg + ': ' : '') +
        'Expected exception of type ' + type.name +
        ' but got ' + e
      );
    }
  }
  if (!threw) {
    throw new Error((msg ? msg + ': ' : '') + 'Expected exception but none thrown');
  }
}

function assertTrue(value, msg) {
  if (!value) {
    throw new Error((msg ? msg + ': ' : '') + 'Expected true');
  }
}

function assertFalse(value, msg) {
  if (value) {
    throw new Error((msg ? msg + ': ' : '') + 'Expected false');
  }
}

// Sandbox helpers. These are stubs; real functionality requires a sandboxed
// V8 build with the Sandbox namespace exposed.
if (typeof Sandbox === 'undefined') {
  globalThis.Sandbox = {
    MemoryView: function () {
      return new DataView(new ArrayBuffer(0));
    },
    getAddressOf: function () {
      return 0n;
    },
    createJSArray: function () {
      return [];
    },
  };
}

// WasmModuleBuilder helpers used by big_sleep-style testcases.
if (typeof kSig_i_v === 'undefined') {
  var kSig_i_v = { params: [], results: [0x7f] };
}
if (typeof kSig_i_i === 'undefined') {
  var kSig_i_i = { params: [0x7f], results: [0x7f] };
}
if (typeof kSig_v_v === 'undefined') {
  var kSig_v_v = { params: [], results: [] };
}
